### ISSUE TITLE
[gpuCI] enable CGA nightly tests

### ISSUE THREAD

**Issue by tijyojwad** [clara-parabricks/ClaraGenomicsAnalysis#402]
Enable nightly tests for `master` and default `dev-vX.Y.Z` branch in CGA repo.

**Comment by ohadmo** [comment]
Fixed in: 
- https://github.com/rapidsai/gpuci-scripts/pull/183  
- https://github.com/rapidsai/gpuci-scripts/pull/187

I created one pipeline for the GPU&CPU jobs (similar to the pull request branch). First, the GPU jobs run in parallel. Once they all finish successfully, the CPU jobs are triggered to be run in parallel.

**Comment by ohadmo** [comment]
Remaining tasks:
- Overwrite branch job name to contain 'cpu_gpu' ([link](https://github.com/rapidsai/gpuci-scripts/blob/d01e9fbb86999aa4ba9cd4227982527a906062ee/seed-job-dsl/seed_job.groovy#L487))
- Overwrite development branch SCM polling time cron expression
- Rename dev packages to contain build number.
